# Generated by Django 5.2.4 on 2025-08-12 17:27

import app.models
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="E'lonlar sarlavhasi")),
                ('views', models.IntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('body', ckeditor.fields.RichTextField(verbose_name='Matn')),
                ('image', models.ImageField(upload_to='news/', validators=[app.models.validate_file_size], verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "E'lon",
                'verbose_name_plural': "E'lonlar",
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/', validators=[app.models.validate_file_size], verbose_name='Rasm')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Rasm',
                'verbose_name_plural': 'Rasmlar',
            },
        ),
        migrations.CreateModel(
            name='VideoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='sarlavha')),
                ('video', models.CharField(help_text='YouTube yoki boshqa video platformalardan video URL manzilini kiriting', max_length=10055, verbose_name='Video URL')),
                ('image', models.ImageField(upload_to='img/', validators=[app.models.validate_file_size], verbose_name='Rasm')),
                ('views', models.IntegerField(default=0, verbose_name="ko'rishlar soni")),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video galereyasi',
                'verbose_name_plural': 'Video galereyalari',
            },
        ),
        migrations.RemoveField(
            model_name='menu',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami'),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mavzu'),
        ),
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.IntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news/', validators=[app.models.validate_file_size], verbose_name='Rasm'),
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Galereya sarlavhasi')),
                ('images', models.ManyToManyField(to='app.photo', verbose_name='Rasmlar')),
            ],
            options={
                'verbose_name': 'Rasm galereyasi',
                'verbose_name_plural': 'Rasm galereyalari',
            },
        ),
    ]
