# Generated by Django 5.2.4 on 2025-08-12 17:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_event_photo_videogallery_remove_menu_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='body_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Matn'),
        ),
        migrations.AddField(
            model_name='event',
            name='body_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Matn'),
        ),
        migrations.AddField(
            model_name='event',
            name='body_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Matn'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name="E'lonlar sarlavhasi"),
        ),
        migrations.AddField(
            model_name='event',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name="E'lonlar sarlavhasi"),
        ),
        migrations.AddField(
            model_name='event',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name="E'lonlar sarlavhasi"),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='Javob'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(null=True, verbose_name='Javob'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_uz',
            field=models.TextField(null=True, verbose_name='Javob'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Savol'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Savol'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Savol'),
        ),
        migrations.AddField(
            model_name='news',
            name='body_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Matn'),
        ),
        migrations.AddField(
            model_name='news',
            name='body_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Matn'),
        ),
        migrations.AddField(
            model_name='news',
            name='body_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Matn'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Yangilik sarlavhasi'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Yangilik sarlavhasi'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Yangilik sarlavhasi'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Kontent'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Kontent'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Kontent'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Sahifa nomi'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Sahifa nomi'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Sahifa nomi'),
        ),
        migrations.AddField(
            model_name='videogallery',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='sarlavha'),
        ),
        migrations.AddField(
            model_name='videogallery',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='sarlavha'),
        ),
        migrations.AddField(
            model_name='videogallery',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='sarlavha'),
        ),
    ]
