# Generated by Django 5.2.4 on 2025-08-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_event_body_en_event_body_ru_event_body_uz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
